services:
  geoserver:
   image: docker.osgeo.org/geoserver:2.24.x
   container_name: geoserver
   restart: always
   ports:
     - ${GS_PORT:-8080}:8080
   volumes:
     - ./geoserver_data:/opt/geoserver/data_dir